version: '2.0'
services: 
  redis:
    container_name: 'redis'
    image: drookie/center-redis:1.2
    command:
      - redis-server
      - /etc/redis.conf
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/redis/redis_lib:/data/redis/redis_lib
      - /data/redis/redis_log:/data/redis/redis_log
    ports:
      - 6379:6379
    restart: always

  mysql:
    container_name: 'mysql'
    image: drookie/center-mysql:1.2
    volumes:
      - /data/mysql/mysql_data:/data/mysql/mysql_data
      - /data/mysql/mysql_log:/data/mysql/mysql_log
    ports:
      - 3306:3306
    restart: always

  mongodb:
    container_name: 'mongodb'
    image: drookie/center-mongodb:1.2
    volumes: 
      - /etc/localtime:/etc/localtime
      - /data/mongodb/mongodb_data:/data/db
      - /data/mongodb/mongodb_log:/data/mongodb/mongodb_log
    ports:
      - 27017:27017
    restart: always

  zookeeper:
    container_name: 'zookeeper'
    image: drookie/center-zookeeper:1.2
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/zookeeper/data:/data
      - /data/zookeeper/datalog:/datalog
    ports:
      - 2181:2181
    restart: always

  kafka:
    container_name: 'kafka'
    image: drookie/center-kafka:1.2
    links:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/kafka:/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://192.168.10.38:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    restart: always

  neo4j:
    container_name: 'neo4j'
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/neo4j/data:/data/neo4j/data
      - /data/neo4j/logs:/data/neo4j/logs
    image: drookie/center-neo4j:1.2
    ports:
      - 7474:7474
      - 7687:7687
    restart: always

  data-center:
    container_name: 'data-center'
    image: drookie/data-center:1.0
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    links:
      - mysql
      - redis
      - kafka
      - zookeeper
      - neo4j
    ports:
      - 9524:9524
    restart: always
    
  map:
    container_name: 'map'
    image: drookie/center-apps-map:1.0
    links:
      - mysql
      - mongodb
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /data/apps/logs:/logs
    ports:
      - 9999:9999
    restart: always
      
  nginx:
    container_name: 'nginx'
    image: drookie/center-nginx:1.2
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/aitensor:/home/aitensor
      - /data/files:/data/files
      - /data/nginx:/var/log/nginx
    links:
      - map
    environment:
      - USB_KEY_URL=http://120.24.223.92:50036/
      - VUE_HOME=/home/aitensor/apps/vue
      - MOCK_URL=http://192.168.10.118:3300
      - LOCAL_FILES_HOME=/data/files/images/
      - IMAGES_HOME=/data/files/images/
    ports:
      - 80:80
    restart: always
