version: '2.0'
services: 
  generic:
    container_name: 'generic'
    image: drookie/center-apps-generic:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9512:9512
    networks:
      - center
    restart: always

  auth:
    container_name: 'auth'
    image: drookie/center-apps-auth:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9513:9513
    networks:
      - center
    restart: always

  address:
    container_name: 'address'
    image: drookie/center-apps-address:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9524:9524
    networks:
      - center
    restart: always

  device:
    container_name: 'device'
    image: drookie/center-apps-device:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9525:9525
    networks:
      - center
    restart: always

  car:
    container_name: 'car'
    image: drookie/center-apps-car:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9531:9531
    networks:
      - center
    restart: always

  face-monitor:
    container_name: 'face-monitor'
    image: drookie/center-apps-face-monitor:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9530:9530
    networks:
      - center
    restart: always

  track:
    container_name: 'track'
    image: drookie/center-apps-track:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9528:9528
    networks:
      - center
    restart: always

  datapush:
    container_name: 'datapush'
    image: drookie/center-apps-datapush:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9526:9526
    networks:
      - center
    restart: always

  pms:
    container_name: 'pms'
    image: drookie/center-apps-pms:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9532:9532
    networks:
      - center
    restart: always

  video:
    container_name: 'video'
    image: drookie/center-apps-video:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9533:9533
    networks:
      - center
    restart: always

  open-api:
    container_name: 'open-api'
    image: drookie/center-apps-open-api:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9534:9534
    networks:
      - center
    restart: always

  face-recognize:
    container_name: 'face-recognize'
    image: drookie/center-apps-face-recognize:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9523:9523
    networks:
      - center
    restart: always

  police:
    container_name: 'police'
    image: drookie/center-apps-police:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9535:9535
    networks:
      - center
    restart: always

  nginx:
    container_name: 'nginx'
    image: drookie/center-nginx:1.2
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /home/aitensor:/home/aitensor
      - /data/files:/data/files
      - /data/nginx/log:/data/nginx/log
      - /data/nginx/conf.d:/etc/nginx/conf.d
    environment:
      - USB_KEY_URL=http://120.24.223.92:50036/
      - VUE_HOME=/home/aitensor/apps/vue
      - MOCK_URL=http://192.168.10.118:3300
      - LOCAL_FILES_HOME=/data/files/images/
      - IMAGES_HOME=/data/files/images/
    ports:
      - 80:80
    networks:
      - center
    restart: always
networks:
  center:
    external: true
