version: '2.0'
services: 
  portainer:
    container_name: 'portainer'
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    restart: always
  featureService:
    container_name: 'featureService'
    image: registry.cn-hangzhou.aliyuncs.com/aitensor-hub/feature-service:1.0
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /data/featureService:/data/featureService
      - /opt:/opt
    ports:
      - 5000:5000
      - 20326:20326
      - 20327:20327
      - 20328:20328
      - 20329:20329
    environment:
      - LOCAL_PORT=5000
      - LOG_LEVEL=0
      - LOG_PATH="/data/featureService/log"
      - THREAD_POOL_NUM=4
      - FACE_INSTANCE=2
      - DEEP_INSTANCE=1
      - REDIS_IP=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_PWD=aitensor@2018
      - MODEL_PATH="/usr/local/featureService/caffe"
      - SERVICE_VERSION=2
      - LOCAL_VERSION=2
      - PLUGIN_PATH="/usr/local/featureService/plugin"
      - RACE_TARGET="cpu"
      - M001_ENABLE=true
      - M001_REMOTE_IP="192.168.10.135"
      - M001_REMOTE_PORT=30332
      - M001_INSTANCE=2
      - M002_ENABLE=true
      - M002_REMOTE_IP="192.168.10.135"
      - M002_REMOTE_PORT=30332
      - M002_INSTANCE=1
      - MAX_LABLES=200000
      - MONITOR_SERVER="127.0.0.1"
      - MONITOR_PORT="80"
      - MONITOR_LOGIN_TARGET="/api/auth/app/token"
      - MONITOR_FACE_POST_TARGET="/api/faceRec/images/batchUpload"
      - MONITOR_CAR_POST_TARGET="/api/car/passRecords/ftpUpload"
      - MONITOR_APP_KEY="community-ftp-001"
      - MONITOR_APP_SECRET="123456"
      - MONITOR_LOG_PATH="/data/folderMonitor/logs"
      - MONITOR_DELETE=0
      - MONITOR_POST_SUCCESS_FOLDER="/data/folderMonitor/success"
      - MONITOR_EMPTY_FILE_FOLDER="/data/folderMonitor/empty"
      - MONITOR_EXTRA_FILE_FOLDER="/data/folderMonitor/extra"
    networks:
      - center
    restart: always
    
  redis:
    container_name: 'redis'
    image: registry.cn-hangzhou.aliyuncs.com/aitensor-hub/center-redis:1.2
    command:
      - redis-server
      - /etc/redis.conf
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /data/redis/redis_lib:/data/redis/redis_lib
      - /data/redis/redis_log:/data/redis/redis_log
    ports:
      - 6379:6379
    networks:
      - center
    restart: always

  mysql:
    container_name: 'mysql'
    image: registry.cn-hangzhou.aliyuncs.com/aitensor-hub/center-mysql:1.2
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /data/mysql/mysql_data:/data/mysql/mysql_data
      - /data/mysql/mysql_log:/data/mysql/mysql_log
    ports:
      - 3306:3306
    networks:
      - center
    restart: always

  mongodb:
    container_name: 'mongodb'
    image: registry.cn-hangzhou.aliyuncs.com/aitensor-hub/center-mongodb:1.2
    volumes: 
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /data/mongodb/mongodb_data:/data/mongodb/mongodb_data
      - /data/mongodb/mongodb_log:/data/mongodb/mongodb_log
    ports:
      - 27017:27017
    networks:
      - center
    restart: always

  zookeeper:
    container_name: 'zookeeper'
    image: zookeeper:3.4.14
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /data/zookeeper/data:/data/zookeeper/data
      - /data/zookeeper/datalog:/data/zookeeper/datalog
      - /data/zookeeper/logs:/data/zookeeper/logs
    environment:
      - ZOO_CONF_DIR=/conf
      - ZOO_DATA_DIR=/data/zookeeper/data
      - ZOO_DATA_LOG_DIR=/data/zookeeper/datalog
      - ZOO_LOG_DIR=/data/zookeeper/logs
      - ZOO_TICK_TIME=2000
      - ZOO_INIT_LIMIT=5
      - ZOO_SYNC_LIMIT=2
      - ZOO_AUTOPURGE_PURGEINTERVAL=0
      - ZOO_AUTOPURGE_SNAPRETAINCOUNT=3
      - ZOO_MAX_CLIENT_CNXNS=60
    ports:
      - 2181:2181
    networks:
      - center
    restart: always

  kafka:
    container_name: 'kafka'
    image: registry.cn-hangzhou.aliyuncs.com/aitensor-hub/center-kafka:1.2
    links:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /data/kafka/log:/data/kafka/log
      - /data/kafka/logs:/opt/kafka/logs
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://192.168.10.38:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LOG_DIRS=/data/kafka/log
    networks:
      - center
    restart: always
    
  neo4j:
    container_name: 'neo4j'
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /data/neo4j/data:/data/neo4j/data
      - /data/neo4j/logs:/data/neo4j/logs
    image: registry.cn-hangzhou.aliyuncs.com/aitensor-hub/center-neo4j:1.2
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - center
    restart: always
      
  gateway:
    container_name: 'gateway'
    image: registry.cn-hangzhou.aliyuncs.com/aitensor-hub/center-apps-gateway:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /data/apps/logs:/logs
      - /data/files:/data/files
    links:
      - mysql
      - nacos
    ports:
      - 9510:9510
    networks:
      - center
    restart: always

  nacos:
    container_name: 'nacos'
    image: registry.cn-hangzhou.aliyuncs.com/aitensor-hub/center-nacos:1.2
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /data/nacos/logs:/home/nacos/logs
      - /data/nacos/data:/home/nacos/data
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_DATABASE_NUM=1
      - MYSQL_MASTER_SERVICE_HOST=mysql
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
      - MYSQL_MASTER_SERVICE_USER=nacos
      - MYSQL_MASTER_SERVICE_PASSWORD=nacos
    links:
      - mysql
    ports:
      - 8848:8848
    networks:
      - center
    restart: always
    
  search:
    container_name: 'search'
    image: registry.cn-hangzhou.aliyuncs.com/aitensor-hub/center-apps-search:3.2.1
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /data/luceneIndex:/home/aitensor/luceneIndex
      - /data/apps/logs:/logs
      - /data/files:/data/files
    ports:
      - 9536:9536
    networks:
      - center
    restart: always
      
  map:
    container_name: 'map'
    image: registry.cn-hangzhou.aliyuncs.com/aitensor-hub/center-apps-map:1.2
    links:
      - mysql
      - mongodb
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /data/apps/logs:/logs
    ports:
      - 9999:9999
    networks:
      - center
    restart: always
  nginx:
    container_name: 'nginx'
    image: registry.cn-hangzhou.aliyuncs.com/aitensor-hub/center-nginx-fdfs:1.2
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor:/home/aitensor
      - /data/files:/data/files
      - /data/nginx/log:/data/nginx/log
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/nginx/fdfs:/etc/fdfs
      - /data/fdfs/tracker:/data/fdfs/tracker
      - /data/fdfs/storage:/data/fdfs/storage
    environment:
      - USB_KEY_URL=http://120.24.223.92:50036/
      - VUE_HOME=/home/aitensor/apps/vue
      - MOCK_URL=http://192.168.10.118:3300
      - LOCAL_FILES_HOME=/data/files/images/
      - IMAGES_HOME=/data/files/images/
      - FDFS_CLIENT_BASE_PATH=/data/fdfs
      - FDFS_TRACKER_BASE_PATH=/data/fdfs/tracker
      - FDFS_TRACKER_PORT=22122
      - FDFS_TRACKER_SERVER=192.168.10.141:22122
      - FDFS_TRACKER_HTTP_SERVER_PORT=8080
      - FDFS_STORAGE_PORT=23000
      - FDFS_STORAGE_HTTP_SERVER_PORT=8888
      - FDFS_STORAGE_BASE_PATH=/data/fdfs/storage
      - FDFS_STORAGE_STORE_PATH0=/data/fdfs/storage
    ports:
      - 80:80
    networks:
      - center
    restart: always
networks:
  center:
    external: true
    
    
    
    
  nginx:
    container_name: 'nginx'
    image: drookie/center-nginx:1.2
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/hosts:/etc/hosts
      - /home/aitensor:/home/aitensor
      - /data/files:/data/files
      - /data/nginx/log:/data/nginx/log
      - /data/nginx/conf.d:/etc/nginx/conf.d
    environment:
      - USB_KEY_URL=http://120.24.223.92:50036/
      - VUE_HOME=/home/aitensor/apps/vue
      - MOCK_URL=http://192.168.10.118:3300
      - LOCAL_FILES_HOME=/data/files/images/
      - IMAGES_HOME=/data/files/images/
    ports:
      - 80:80
    networks:
      - center
    restart: always
