version: '1.0'
services: 
  redis:
    container_name: 'redis'
    image: drookie/center-redis:1.0
    volumes:
      - /data/redis:/data/redis
    ports:
      - 6379:6379
  mysql:
    container_name: 'mysql'
    image: drookie/center-mysql:1.0
    volumes:
      - /data/mysql:/data/mysql
    ports:
      - 3306:3306
  mongodb:
    container_name: 'mongodb'
    image: drookie/center-mongodb:1.0
    volumes: 
      - /data/mongodb:/data/mongodb
    ports:
      - 27017:27017
  zookeeper:
    container_name: 'zookeeper'
    image: drookie/center-zookeeper:1.0
    volumes:
      - /data/zookeeper/data:/data
      - /data/zookeeper/datalog:/datalog
    ports:
      - 2181:2181
  kafka:
    container_name: 'kafka'
    image: drookie/center-kafka:1.0
    links:
      - zookeeper
    ports:
      - 9092:9092
    volumes:
      - /Users/wjy/data/kafka:/kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=192.168.10.38
      - KAFKA_ADVERTISED_PORT=9092
  neo4j:
    container_name: 'neo4j'
    volumes:
    image: drookie/center-neo4j:1.0
    ports:
      - 7474:7474
      - 7687:7687
  nacos:
    container_name: 'nacos'
    image: drookie/center-nacos:1.0
    ports:
      - 8848:8848
  nginx:
    container_name: 'nginx'
    image: drookie/center-nginx:1.0
    volumes:
      - /Users/wjy/data/aitensor:/home/aitensor
    ports:
      - 80:80