version: '2.0'
services: 
  redis:
    container_name: 'redis'
    image: drookie/center-redis:1.0
    volumes:
      - /data/redis:/data/redis
    ports:
      - 6379:6379

  mysql:
    container_name: 'mysql'
    image: drookie/center-mysql:1.0
    volumes:
      - /data/mysql:/data/mysql
    ports:
      - 3306:3306

  mongodb:
    container_name: 'mongodb'
    image: drookie/center-mongodb:1.0
    volumes: 
      - /data/mongodb:/data/mongodb
    ports:
      - 27017:27017

  zookeeper:
    container_name: 'zookeeper'
    image: drookie/center-zookeeper:1.0
    volumes:
      - /data/zookeeper/data:/data
      - /data/zookeeper/datalog:/datalog
    ports:
      - 2181:2181

  kafka:
    container_name: 'kafka'
    image: drookie/center-kafka:1.0
    links:
      - zookeeper
    ports:
      - 9092:9092
    volumes:
      - /data/kafka:/kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=192.168.10.38
      - KAFKA_ADVERTISED_PORT=9092

  neo4j:
    container_name: 'neo4j'
    volumes:
      - /data/neo4j/data:/data
    image: drookie/center-neo4j:1.0
    ports:
      - 7474:7474
      - 7687:7687
  gateway:
    container_name: 'gateway'
    image: drookie/center-apps-gateway:3.2
    volumes:
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
    ports:
      - 9510:9510

  nacos:
    container_name: 'nacos'
    image: drookie/center-nacos:1.0
    volumes:
      - /data/nacos/logs:/home/nacos/logs
      - /data/nacos/data:/home/nacos/data
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_DATABASE_NUM=1
      - MYSQL_MASTER_SERVICE_HOST=mysql
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
      - MYSQL_MASTER_SERVICE_USER=nacos
      - MYSQL_MASTER_SERVICE_PASSWORD=nacos
    links:
      - mysql
    ports:
      - 8848:8848

  nginx:
    container_name: 'nginx'
    image: drookie/center-nginx:1.0
    volumes:
      - /home/aitensor:/home/aitensor
    ports:
      - 80:80

  generic:
    container_name: 'generic'
    image: drookie/center-apps-generic:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
    ports:
      - 9512:9512

  auth:
    container_name: 'auth'
    image: drookie/center-apps-auth:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
    ports:
      - 9513:9513

  address:
    container_name: 'address'
    image: drookie/center-apps-address:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
      - neo4j
    ports:
      - 9524:9524

  device:
    container_name: 'device'
    image: drookie/center-apps-device:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
    ports:
      - 9525:9525

  car:
    container_name: 'car'
    image: drookie/center-apps-car:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
      - mongodb
    ports:
      - 9531:9531

  face-monitor:
    container_name: 'face-monitor'
    image: drookie/center-apps-face-monitor:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
      - mongodb
    ports:
      - 9530:9530

  track:
    container_name: 'track'
    image: drookie/center-apps-track:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
      - mongodb
    ports:
      - 9528:9528

  datapush:
    container_name: 'datapush'
    image: drookie/center-apps-datapush:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
      - mongodb
    ports:
      - 9526:9526

  pms:
    container_name: 'pms'
    image: drookie/center-apps-pms:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
      - mongodb
    ports:
      - 9532:9532

  video:
    container_name: 'video'
    image: drookie/center-apps-video:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
      - mongodb
    ports:
      - 9533:9533

  open-api:
    container_name: 'open-api'
    image: drookie/center-apps-open-api:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
    ports:
      - 9534:9534

  face-recognize:
    container_name: 'face-recognize'
    image: drookie/center-apps-face-recognize:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
      - mongodb
    ports:
      - 9523:9523

  police:
    container_name: 'police'
    image: drookie/center-apps-police:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /data/apps/logs:/logs
    links:
      - mysql
      - nacos
      - redis
      - kafka
      - mongodb
    ports:
      - 9535:9535

  search:
    container_name: 'search'
    image: drookie/center-apps-generic:3.2
    volumes:
      - /home/aitensor/lib:/home/aitensor/lib
      - /home/aitensor/luceneIndex:/home/aitensor/luceneIndex
      - /data/apps/logs:/logs
    ports:
      - 9536:9536

  











